@_default:
    just --list

# format the Justfile
@fmt:
    just --fmt --unstable

#-----------------------------------------------------------
# Bootstrap
#-----------------------------------------------------------

# copy .env.example to .env
@dotenv:
    echo "💉 Copying .env.example to .env"
    cp .env.example .env
    echo "✨ .env written successfully"
    echo "💡 Done. Remember to update and source .env"

# remove secrets
cleanup:
    echo "Removing .env file"
    rm .env

#-----------------------------------------------------------
# Terraform Backend
#-----------------------------------------------------------
setup-r2-bucket:
    echo "🪣 Ensuring {{ cookiecutter.r2_bucket_name}} R2 Bucket exists"

#-----------------------------------------------------------
# Terraform
#-----------------------------------------------------------

# output a single resource
tf-output resource:
    terraform output -json {{ "{{ resource }}" }}

# outputs all resources
tf-outputs:
    terraform output -json
